### PR TITLE
Add import from ttl rdf

### LINKED ISSUE #196: Implement import functionality
Story: 

1. Create a vocab in Neologism
2. Download TTL
3. Edit TTL offline (e.g., via text editor)
4. Upload TTL again and proceed in Neologism

### PR DESCRIPTION
**Pull request by alihussainiam**
closes #196

### CODE REVIEW

**Comment by alihussainiam** [comment]
Notes: Along with import found two bugs. One has been fixed which can be found at [commit](https://github.com/Semantic-Society/Neologism/pull/202/commits/74ffd0e57febcd7fa9257ad634e01d75d148081e). For the other  issue #203  has been created

**Comment by JohannesLipp** [comment]
@IraklisDimitriadis can you help reviewing this? My Angular skills are not too strong :)

**Comment by IraklisDimitriadis** [comment]
@JohannesLipp sure, I'll review it by tomorrow

**Comment by JohannesLipp** [comment]
> @JohannesLipp sure, I'll review it by tomorrow

Thank you!

**Comment by IraklisDimitriadis** [comment]
> > @JohannesLipp sure, I'll review it by tomorrow
> 
> Thank you!
Looks good to me

**Pull request merged**
